title: Swati S Bhat
# email: your-email@example.com
# description:
baseurl: '/'
url: 'https://swatisbhat.github.io'

github_username: swatisbhat
linkedin_username: swati-s-bhat
twitter_username: SwatiSB4
goodreads_username: swatisb

header_pages:
    - index.markdown
    - experience.markdown

show_excerpts: true
# Build settings
theme: minima
plugins:
    - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
